"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
from time import time
from datetime import timedelta
from django.utils.http import http_date

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '^$hy!f()*fku_95gh)w_tnuq62@emm)b!!+vv(8_0)ihnr5r_^'

ENV = os.getenv('ENV', 'LOCAL')

NSS_DATABASE_USER = os.getenv('DATABASE_USER', 'root')
NSS_DATABASE_PASSWORD = os.getenv('DATABASE_PASSWORD', 'root')
NSS_DATABASE_HOST = os.getenv('DATABASE_HOST', 'localhost')
NSS_DATABASE_PORT = os.getenv('DATABASE_PORT', '3306')
NSS_DATABASE_NAME = os.getenv('DATABASE_NAME', 'django_test')

NSS_AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID', 'AKIAJYMWT23ENVVXRK7Q')
NSS_AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY', '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')
NSS_AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME', 'nssdevelop')

NSS_USE_JWT = os.getenv('USE_JWT', True)
NSS_JWT_SECRET_KEY = os.getenv('JWT_SECRET_KEY', SECRET_KEY)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = ENV == 'LOCAL'

ALLOWED_HOSTS = ['*']
APPEND_SLASH=False


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'oauth2_provider',
    'rest_framework',
    'core',
    'security',
    'users'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, "templates")
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': NSS_DATABASE_NAME,
        'USER': NSS_DATABASE_USER,
        'PASSWORD': NSS_DATABASE_PASSWORD,
        'HOST': NSS_DATABASE_HOST,
        'PORT': NSS_DATABASE_PORT
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_VERSION = time()

AWS_ACCESS_KEY_ID = NSS_AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY = NSS_AWS_SECRET_ACCESS_KEY
AWS_STORAGE_BUCKET_NAME = NSS_AWS_STORAGE_BUCKET_NAME

STATIC_ROOT = os.path.join(BASE_DIR, "static")
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

if ENV == 'LOCAL':
    STATIC_URL = '/static/'
    MEDIA_URL = '/media/'

JWT_EXPIRATION_DELTA = timedelta(minutes=50)

if NSS_USE_JWT:    
    JWT_AUTH = {
        'JWT_SECRET_KEY': NSS_JWT_SECRET_KEY,
        'JWT_RESPONSE_PAYLOAD_HANDLER': 'core.custom_jwt_response.jwt_response_payload_handler',
        'JWT_EXPIRATION_DELTA': JWT_EXPIRATION_DELTA
    }

CORS_ORIGIN_ALLOW_ALL = True
